---
title: "主要研究成果"
description: "科研成果展示"
output:
  html_document:
    theme: cosmo
    toc: false
---


## 代表性论文
1. 吴孔杰, 胡承孝, 谭启玲, 孙学成, 赵小虎, 武松伟*. 柑橘果实糖积累特征及蔗糖转运机制研究进展. 园艺学报, 2022, 49: 2543-2558.
2. Songwei Wu, Xuecheng Sun, Qiling Tan, Chengxiao Hu*. Molybdenum improves water uptake via extensive root morphology, aquaporin expressions and increased ionic concentrations in wheat under drought stress. Environmental and Experimental Botany, 2019 (157): 241-249.
3. Songwei Wu, Chengxiao Hu, Qiling Tan, Xiaohu Zhao, Shoujun Xu, Yitao Xia, Xuecheng Sun*. Nitric oxide acts downstream of abscisic acid in molybdenum-induced oxidative tolerance in wheat. Plant Cell Reports, 2018, 37:599-610.
4. Songwei Wu, Changming Zhang, Ming Li, Qiling Tan, Xuecheng Sun, Zhiyong Pan, Xiuxin Deng, Chengxiao Hu*. Effects of potassium on fruit soluble sugar and citrate accumulations in Cara Cara navel orange (Citrus sinensis L. Osbeck), Scientia Horticulturae, 2021 (283): 110057.
5. Songwei Wu, Ming Li, Changming Zhang, Qiling Tan, Xiaozhen Yang, Xuecheng Sun, Zhiyong Pan, Xiuxin Deng, Chengxiao Hu*. Effects of phosphorus on fruit soluble sugar and citric acid accumulations in citrus, Plant Physiology and Biochemistry, 2021 (160): 73-81.
6. Songwei Wu , Kongjie Wu , .... Chengxiao Hu*. Recruitment of specific microbes through exudates affects cadmium activation and accumulation in Brassica napus. Journal of Hazardous Materials. 442 (2023) 130066.

## 科研项目
- 国家现代柑橘产业技术体系，养分管理与化肥减施增效（CARS-26），2024.01-至今，主持，在研
- 国家重点研发计划子课题，柑橘水肥精准施用技术研发与应用研究（2024YFD2300801），2024.12-2027.12，主持，在研
- 国家自然科学基金青年基金，钾提高柑橘果实柠檬酸积累的生理和分子机制， 2021.01-2023.12，主持，结题
- 国家重点研发计划子课题，钾营养调控柑橘果实糖累积的生理机制， 2020.01-2022.12，主持，结题


## 奖励与荣誉
- 2024年，湖北省科技进步二等奖（5/10）
- 2023年，中国植物营养与肥料学会科技进步奖二等奖（6/14）
- 2018年，中国中微肥创新联盟青年英才奖（1/1）
